name: Publish Docker image to Docker Hub
on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - uses: actions/checkout@v3
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          server-id: docker.io
          server-username: DOCKER_USERNAME
          server-password: DOCKER_PASSWORD
      - name: Build package
        run: mvn --batch-mode clean package
      - name: Build and push image
        run: mvn --batch-mode -pl webprotege-gwt-ui-server dockerfile:build dockerfile:push

env:
  DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
  DOCKER_TOKEN: ${{secrets.DOCKER_PASSWORD}}